name: Reviewdog


on:
    pull_request:

permissions:
    contents: read
    pull-requests: write
    checks: write

jobs:
    detekt:
        name: Detekt with Reviewdog
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up JDK
              uses: actions/setup-java@v4
              with:
                  distribution: temurin
                  java-version: 17

            - name: Make Gradle executable
              run: chmod +x ./gradlew

            - name: Run Detekt
              run: ./gradlew detekt --continue
              continue-on-error: true

            - name: Set up Reviewdog
              uses: reviewdog/action-setup@v1

            - name: Run Reviewdog for Detekt
              env:
                  REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  REPORTS=$(find . -path "*/build/reports/detekt/detekt.xml")
                  if [ -z "$REPORTS" ]; then
                    echo "No Detekt reports found."
                    exit 0
                  fi
                  cat $REPORTS | reviewdog \
                    -f=checkstyle \
                    -name="detekt" \
                    -reporter=github-pr-review \
                    -filter-mode=diff_context \
                    -fail-on-error=false

    ktlint:
        name: Ktlint with Reviewdog
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up JDK
              uses: actions/setup-java@v4
              with:
                  distribution: temurin
                  java-version: 17

            - name: Make Gradle executable
              run: chmod +x ./gradlew

            - name: Run Ktlint
              run: ./gradlew ktlintCheck --continue
              continue-on-error: true

            - name: Set up Reviewdog
              uses: reviewdog/action-setup@v1

            - name: Run Reviewdog for Ktlint
              env:
                  REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  REPORTS=$(find . -path "*/build/reports/ktlint/*.xml")
                  if [ -z "$REPORTS" ]; then
                    echo "No Ktlint reports found."
                    exit 0
                  fi
                  cat $REPORTS | reviewdog \
                    -f=checkstyle \
                    -name="ktlint" \
                    -reporter=github-pr-review \
                    -filter-mode=diff_context \
                    -fail-on-error=false
